package com.zylitics.btbr.webdriver;

import com.google.cloud.storage.Storage;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.ImmutableList;
import com.zylitics.btbr.config.APICoreProperties;
import com.zylitics.btbr.model.BuildCapability;
import com.zylitics.btbr.webdriver.functions.action.DragAndDrop;
import com.zylitics.btbr.webdriver.functions.action.PerformAction;
import com.zylitics.btbr.webdriver.functions.action.Scroll;
import com.zylitics.btbr.webdriver.functions.color.ColorMatches;
import com.zylitics.btbr.webdriver.functions.context.*;
import com.zylitics.btbr.webdriver.functions.context.resize.*;
import com.zylitics.zwl.interpret.Function;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.io.PrintStream;
import java.nio.file.Path;
import java.util.List;

public class WebdriverFunctions {
  
  private final APICoreProperties.Webdriver wdProps;
  
  private final BuildCapability buildCapability;
  
  private final RemoteWebDriver driver;
  
  private final PrintStream printStream;
  
  private final Storage storage;
  
  private final String userAccountBucket;
  
  private final String pathToUploadedFiles;
  
  private final Path buildDir;
  
  public WebdriverFunctions(APICoreProperties.Webdriver wdProps,
                            BuildCapability buildCapability,
                            RemoteWebDriver driver,
                            PrintStream printStream,
                            Storage storage,
                            String userAccountBucket,
                            String pathToUploadedFiles,
                            Path buildDir) {
    Preconditions.checkNotNull(wdProps, "wdProps can't be null");
    Preconditions.checkNotNull(buildCapability, "buildCapability can't be null");
    Preconditions.checkNotNull(driver, "driver can't be null");
    Preconditions.checkNotNull(printStream, "printStream can't be null");
    Preconditions.checkNotNull(storage, "storage can't be null");
    Preconditions.checkArgument(!Strings.isNullOrEmpty(userAccountBucket),
        "userAccountBucket can't be empty");
    Preconditions.checkArgument(!Strings.isNullOrEmpty(pathToUploadedFiles),
        "pathToUploadedFiles can't be empty");
    Preconditions.checkNotNull(buildDir, "buildDir can't be null");
    
    this.wdProps = wdProps;
    this.buildCapability = buildCapability;
    this.driver = driver;
    this.printStream = printStream;
    this.storage = storage;
    this.userAccountBucket = userAccountBucket;
    this.pathToUploadedFiles = pathToUploadedFiles;
    this.buildDir = buildDir;
  }
  
  List<Function> get() {
    ImmutableList.Builder<Function> builder = ImmutableList.builder();
    builder.add(
        // action
        new DragAndDrop(wdProps, buildCapability, driver, printStream),
        new PerformAction(wdProps, buildCapability, driver, printStream),
        new Scroll(wdProps, buildCapability, driver, printStream),
        new ColorMatches(wdProps, buildCapability, driver, printStream),
        new Close(wdProps, buildCapability, driver, printStream),
        new GetAllWinIds(wdProps, buildCapability, driver, printStream),
        new GetCurrentWinId(wdProps, buildCapability, driver, printStream),
        new NewWin(wdProps, buildCapability, driver, printStream),
        new SwitchFrame(wdProps, buildCapability, driver, printStream),
        new SwitchParentFrame(wdProps, buildCapability, driver, printStream),
        new SwitchWin(wdProps, buildCapability, driver, printStream),
        new FullScreenWin(wdProps, buildCapability, driver, printStream),
        new GetWinPosition(wdProps, buildCapability, driver, printStream),
        new GetWinSize(wdProps, buildCapability, driver, printStream),
        new MaximizeWin(wdProps, buildCapability, driver, printStream),
        new MoveWinBy(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        new xxx(wdProps, buildCapability, driver, printStream),
        
    );
    return builder.build();
  }
}
