---
api-core:
  project-id: zl-win-nodes
  cloud-kms:
    key-ring: zl-apps-auth-secret
    key: default-prod
    key-bucket: zl-secrets
  esdb:
    auth-user: elastic
    auth-user-secret-cloud-file: zl-esdb-auth.encrypt
    max-retries: 10
    shot-metadata-index: bt_shot_metadata
    zwl-program-output-index: zwl_program_output
    env-var-host: ESDB_HOST
  data-source:
    db-name: zbtp
    user-name: zbtp
    user-secret-cloud-file: zbtp-auth.encrypt
    # the private IP of instance, such as 10.11.12.9. CloudSql keeps the default 5432 port thus,
    # no need to mention that.
    private-host-cloud-file: zl-pgdb-private-host.encrypt
    # small idle connections because this app works for a single session only and mostly just one
    # thread will seek synchronous access to pgdb. see
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    min-idle-conn-pool: 2
  runner:
    program-output-flush-no: 5
    # later we may give it as build caps too for custom values, this is done so that non-webdriver
    # code (which executes in microseconds) wouldn't put lot of load on db.
    update-line-build-status-after: 1000
    label-key-availability-status: availability-status
    label-value-availability-status: FREE
    wzgp-endpoint: https://wzgp.api.zylitics.io
    wzgp-version: beta
    wzgp-auth-user: prod-test
    wzgp-auth-secret-cloud-file: zl-wzgp-prod-test-auth.encrypt
  shot:
    ext: png
    content-type: image/png
    # large wait time for the largest running builds
    max-shot-finish-sec: 7200
    error-shot: ERROR
    eos-shot: EOS
    shot-metadata-flush-records: 100
  webdriver:
    server-logs-bucket: zl-server-logs
    user-data-bucket: zl-user-data
    # this bucket keeps things like user uploaded files for testing file input in builds
    # etc.
    user-uploads-storage-dir-tmpl : USER_ID/uploads
    supported-browsers:
      - chrome
      - firefox
      - internet explorer
    supported-platforms:
      - windows
    default-page-load-strategy: eager
    default-timeout-element-access: 60000
    # Following timeout settings must remain same as webdriver defaults because we use them to reset
    # timeouts of webdriver unless user asks otherwise.
    default-timeout-page-load: 300000 # must be same as the default for webdriver
    default-timeout-script: 30000 # must be same as the default for webdriver
    default-timeout-new-window: 30000
    ie-default-browser-attach-timeout: 5000
    ie-default-file-upload-dialog-timeout: 5000
    enable-profiler-logs-prop: webdriver.logging.profiler.enabled
    verbose-client-logs-prop: webdriver.logging.client.verbose.enabled
    browser-perf-logs-dir: performance-logs
    internal-logs-dir: all-internal-logs
    driver-logs-dir: driver-logs
    browser-perf-logs-file: performance.log
    client-logs-file: client.log
    profiler-logs-file: profiler.log
    driver-logs-file: driver.log
    wait-between-logs-capture: 10000
    element-shot-dir: element-shot
---
